In [36]:
import pandas as pd
import numpy as np

In [37]:
df = pd.read_csv('pesquisa_satisfacao.csv', sep=';')
df

         Cliente Satisfação  Tempo de Espera (min)
0         Naruto       Alta                      8
1           Goku       Alta                     10
2         Vegeta      Média                     17
3         Sasuke       Alta                      8
4         Madara      Média                     15
5          Luffy      Baixa                      5
6           Zoro       Alta                     22
7          Sanji      Baixa                     26
8         Yusuke      Baixa                     14
9         Kurama      Média                      8
10           Gon      Média                     12
11          Eren      Média                     28
12        Mikasa       Alta                      6
13         Light       Alta                     10
14             L       Alta                     19
15  Peter Parker      Baixa                     21
16   Bruce Wayne       Alta                     18
17        Thanos      Média                     19
18       Edmundo      Baixa                     13
19       Vegetti      Média                     19

In [38]:
media_satisfacao = df.groupby ('Satisfação') ['Tempo de Espera (min)'].mean().reset_index()
media_satisfacao['Tempo de Espera (min)'] = round (media_satisfacao['Tempo de Espera (min)'], 2)
media_satisfacao

  Satisfação  Tempo de Espera (min)
0       Alta                  12.62
1      Baixa                  15.80
2      Média                  16.86

In [39]:
df_anp = pd.read_csv('ANP2025.csv', sep=';')
df_anp

C:\Users\luiz.gutemberg\AppData\Local\Temp\ipykernel_5564\3435742200.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  df_anp = pd.read_csv('ANP2025.csv', sep=';')

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN
3,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,ETANOL,01/01/2025,"5,19",NaN,R$ / litro,RAIZEN
4,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,GASOLINA,01/01/2025,"6,53",NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
df_anp_rj = df_anp.loc[df_anp['Estado - Sigla'] == 'RJ']
df_anp_rj.head(5)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
54,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,GNV,01/01/2025,"5,39",NaN,R$ / m³,VIBRA
55,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,GASOLINA,01/01/2025,"6,49",NaN,R$ / litro,VIBRA
56,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,GASOLINA ADITIVADA,01/01/2025,"6,69",NaN,R$ / litro,VIBRA
57,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS CONTORNO DE CAMPOS LTDA,31.212.889/0002-85,AVENIDA NILO PECANHA,614,/822 PATIO,PQ SANTO AMARO,28030-035,ETANOL,01/01/2025,"4,79",NaN,R$ / litro,VIBRA
58,SE,RJ,CAMPOS DOS GOYTACAZES,POSTO DE COMBUSTIVEIS B J LTDA,06.211.735/0001-40,RUA BENEDITO QUEIROZ,1,NaN,TURF CLUB,28024-040,GASOLINA,01/01/2025,"6,42",NaN,R$ / litro,BRANCA

In [41]:
df_anp_rj['Valor de Venda'] = df_anp_rj['Valor de Venda'].str.replace(',', '.').astype(float)

C:\Users\luiz.gutemberg\AppData\Local\Temp\ipykernel_5564\3075155369.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_anp_rj['Valor de Venda'] = df_anp_rj['Valor de Venda'].str.replace(',', '.').astype(float)

In [42]:
media_munc_rj = df_anp_rj.groupby('Municipio') ['Valor de Venda'].mean().reset_index()
media_munc_rj = media_munc_rj.sort_values (by = 'Valor de Venda', ascending = False)
media_munc_rj.head (5)

         Municipio  Valor de Venda
0   ANGRA DOS REIS        6.470086
10           MACAE        6.224548
24       TRES RIOS        6.206138
2   BARRA DO PIRAI        6.168793
23       SAQUAREMA        6.070452

In [43]:
arry_valor_venda = np.array (media_munc_rj['Valor de Venda'])

In [44]:
media = np.mean (arry_valor_venda)
mediana = np.median (arry_valor_venda)

q1 = np.quantile (arry_valor_venda, 0.25)
q2 = np.quantile (arry_valor_venda, 0.50)
q3 = np.quantile (arry_valor_venda, 0.75)

print(f'A média é {media}')
print (f'A mediana é {mediana}')
print (f'Primeiro quartil é (Q1){q1}')
print (f'Segundo quartil é (Q2){q2}')
print (f'Terceiro quartil é (Q3){q3}')

A média é 5.856684177816972
A mediana é 5.891806930693069
Primeiro quartil é (Q1)5.588252288329519
Segundo quartil é (Q2)5.891806930693069
Terceiro quartil é (Q3)6.047136868364782

In [45]:
munic_acima_q3 = media_munc_rj.loc[media_munc_rj['Valor de Venda'] > q3]
munic_acima_q3

         Municipio  Valor de Venda
0   ANGRA DOS REIS        6.470086
10           MACAE        6.224548
24       TRES RIOS        6.206138
2   BARRA DO PIRAI        6.168793
23       SAQUAREMA        6.070452
9        ITAPERUNA        6.069675
16      PETROPOLIS        6.064262

In [54]:
df_rj_etanol = df_anp.loc [(df_anp['Municipio'] == 'RIO DE JANEIRO') & (df_anp['Produto'] == 'ETANOL')]
df_rj_etanol

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
1000,SE,RJ,RIO DE JANEIRO,POSTO MANÉ GARRINCHA DE BOTAFOGO LTDA.,07.877.289/0001-70,RUA VOLUNTARIOS DA PATRIA,308,NaN,BOTAFOGO,22270-010,ETANOL,02/01/2025,"4,49",NaN,R$ / litro,RAIZEN
1004,SE,RJ,RIO DE JANEIRO,POSTO DE GASOLINA GASOAL LTDA,05.159.154/0001-44,RUA VINTE E QUATRO DE MAIO,871,NaN,ENGENHO NOVO,20950-091,ETANOL,02/01/2025,"4,09",NaN,R$ / litro,BRANCA
1009,SE,RJ,RIO DE JANEIRO,POSTO CATEDRAL LTDA,27.838.044/0001-41,AVENIDA MEM DE SA,55,NaN,CENTRO,20230-150,ETANOL,02/01/2025,"4,49",NaN,R$ / litro,RAIZEN
1013,SE,RJ,RIO DE JANEIRO,POSTO PALACIO GUANABARA LTDA,04.816.108/0001-08,RUA PINHEIRO MACHADO,83,83/FUNDOS,LARANJEIRAS,22231-090,ETANOL,02/01/2025,"4,69",NaN,R$ / litro,RAIZEN
1018,SE,RJ,RIO DE JANEIRO,AUTO POSTO ATERRO DO FLAMENGO LTDA,01.309.199/0001-05,AVENIDA INFANTO DOM HENRIQUE,S/N,NaN,FLAMENGO,20021-140,ETANOL,02/01/2025,"5,70",NaN,R$ / litro,VIBRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418188,SE,RJ,RIO DE JANEIRO,POSTO DE GASOLINA CIDADE DE DEUS LTDA,11.333.439/0001-52,ESTRADA DO GABINAL,1955,NaN,CIDADE DE DEUS,22763-153,ETANOL,30/06/2025,"4,19",NaN,R$ / litro,IPIRANGA
418246,SE,RJ,RIO DE JANEIRO,BARRA GAS COMERCIO E SERVICOS LTDA,11.513.372/0001-38,AVENIDA AYRTON SENNA,9201,NaN,JACAREPAGUA,22775-004,ETANOL,30/06/2025,"4,29",NaN,R$ / litro,IPIRANGA
418257,SE,RJ,RIO DE JANEIRO,CENTRO DE ABASTECIMENTO CHESSED LTDA,11.054.754/0001-40,AVENIDA AMARO CAVALCANTI,2554,A 2562 LOJA,ENGENHO DE DENTRO,20735-042,ETANOL,30/06/2025,"4,09",NaN,R$ / litro,BRANCA
418842,SE,RJ,RIO DE JANEIRO,AUTO POSTO LUAR DA RIO SANTOS II LTDA,11.217.808/0001-41,ESTRADA DO GUANDU ESQ.C/ BR 101,SN,KM 388 AREA REM III LOTE 210 SENTIDO RJ,SANTA CRUZ,23560-150,ETANOL,30/06/2025,"4,29",NaN,R$ / litro,RAIZEN
419214,SE,RJ,RIO DE JANEIRO,AUTO POSTO LUAR DA RIO SANTOS I LTDA,11.103.499/0001-89,ESTRADA DO GANDU ESQ C/BR101,SN,KM 388 AREA REM I LOTE 209 SENTIDO ANGRA,SANTA CRUZ,23560-150,ETANOL,30/06/2025,"4,39",NaN,R$ / litro,RAIZEN

In [64]:
df_rj_etanol = df_anp.loc [(df_anp['Municipio'] == 'RIO DE JANEIRO') & (df_anp['Produto'] == 'ETANOL')]
df_rj_etanol

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
1000,SE,RJ,RIO DE JANEIRO,POSTO MANÉ GARRINCHA DE BOTAFOGO LTDA.,07.877.289/0001-70,RUA VOLUNTARIOS DA PATRIA,308,NaN,BOTAFOGO,22270-010,ETANOL,02/01/2025,"4,49",NaN,R$ / litro,RAIZEN
1004,SE,RJ,RIO DE JANEIRO,POSTO DE GASOLINA GASOAL LTDA,05.159.154/0001-44,RUA VINTE E QUATRO DE MAIO,871,NaN,ENGENHO NOVO,20950-091,ETANOL,02/01/2025,"4,09",NaN,R$ / litro,BRANCA
1009,SE,RJ,RIO DE JANEIRO,POSTO CATEDRAL LTDA,27.838.044/0001-41,AVENIDA MEM DE SA,55,NaN,CENTRO,20230-150,ETANOL,02/01/2025,"4,49",NaN,R$ / litro,RAIZEN
1013,SE,RJ,RIO DE JANEIRO,POSTO PALACIO GUANABARA LTDA,04.816.108/0001-08,RUA PINHEIRO MACHADO,83,83/FUNDOS,LARANJEIRAS,22231-090,ETANOL,02/01/2025,"4,69",NaN,R$ / litro,RAIZEN
1018,SE,RJ,RIO DE JANEIRO,AUTO POSTO ATERRO DO FLAMENGO LTDA,01.309.199/0001-05,AVENIDA INFANTO DOM HENRIQUE,S/N,NaN,FLAMENGO,20021-140,ETANOL,02/01/2025,"5,70",NaN,R$ / litro,VIBRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418188,SE,RJ,RIO DE JANEIRO,POSTO DE GASOLINA CIDADE DE DEUS LTDA,11.333.439/0001-52,ESTRADA DO GABINAL,1955,NaN,CIDADE DE DEUS,22763-153,ETANOL,30/06/2025,"4,19",NaN,R$ / litro,IPIRANGA
418246,SE,RJ,RIO DE JANEIRO,BARRA GAS COMERCIO E SERVICOS LTDA,11.513.372/0001-38,AVENIDA AYRTON SENNA,9201,NaN,JACAREPAGUA,22775-004,ETANOL,30/06/2025,"4,29",NaN,R$ / litro,IPIRANGA
418257,SE,RJ,RIO DE JANEIRO,CENTRO DE ABASTECIMENTO CHESSED LTDA,11.054.754/0001-40,AVENIDA AMARO CAVALCANTI,2554,A 2562 LOJA,ENGENHO DE DENTRO,20735-042,ETANOL,30/06/2025,"4,09",NaN,R$ / litro,BRANCA
418842,SE,RJ,RIO DE JANEIRO,AUTO POSTO LUAR DA RIO SANTOS II LTDA,11.217.808/0001-41,ESTRADA DO GUANDU ESQ.C/ BR 101,SN,KM 388 AREA REM III LOTE 210 SENTIDO RJ,SANTA CRUZ,23560-150,ETANOL,30/06/2025,"4,29",NaN,R$ / litro,RAIZEN
419214,SE,RJ,RIO DE JANEIRO,AUTO POSTO LUAR DA RIO SANTOS I LTDA,11.103.499/0001-89,ESTRADA DO GANDU ESQ C/BR101,SN,KM 388 AREA REM I LOTE 209 SENTIDO ANGRA,SANTA CRUZ,23560-150,ETANOL,30/06/2025,"4,39",NaN,R$ / litro,RAIZEN